version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:14.15.4-browsers
        environment:
          NO_SANDBOX: true
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm test
      - run:
          command: npm run build
      - run:
          command: npm run lint
      - run:
          command: npm run storybook:build
