version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    docker:
      - image: cimg/node:14.15.4-browsers
        environment:
          NO_SANDBOX: true
    steps:
      - checkout
      - run:
          command: npm ci
      - run:
          command: npm run lint
      - run:
          command: npm test
      - run:
          command: npm run build
      - run:
          command: npm run storybook:build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: olizilla/ipfs-dns-deploy
        environment:
          BUILD_DIR: build
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Add to IPFS
          command: |
            pin_name="ipld-explorer-components build $CIRCLE_BUILD_NUMBER"
            hash=$(pin-to-cluster.sh "$pin_name" /tmp/workspace/$BUILD_DIR)
            echo "Website added to IPFS: https://dweb.link/ipfs/$hash"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: ipfs-dns-deploy
          requires:
            - build
